#theme: jekyll-theme-minimal
title: Vera Ko
description: verako3@gmail.com
#logo: img src="https://github.com/ko-vera/ko-vera.github.io/assets/91451073/cd6c7775-5e18-4cb7-b367-4364af5e81c0" width="100"

#show_downloads: true

