title: <font color = "#2B547E"> Vera Ko </font> <img src="https://github.com/ko-vera/ko-vera.github.io/assets/91451073/cd6c7775-5e18-4cb7-b367-4364af5e81c0" width="30">
#description: Integrated Engineering Student - Mechanical & Electrical
#logo: img src="https://github.com/ko-vera/ko-vera.github.io/assets/91451073/cd6c7775-5e18-4cb7-b367-4364af5e81c0" width="100"
#theme: jekyll-theme-minimal
#show_downloads: true

